import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="flex justify-center items-center flex-col h-screen">
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center flex-col">
        <Image src="/vercel.svg" height={100} width={200} />
        <h1 className="my-4 text-6xl font-bold">Expense Tracker</h1>
      </main>

      <footer className="border-t-2 fixed bottom-0 h-20 w-full flex justify-center items-center">
        <h1>Made by <span className="font-bold underline">Mukul Rajpoot</span></h1>
      </footer>

    </div>
  )
}
